# Please move me to a proper location
class String
  def property_name
    underscore.gsub('/','__').gsub('::','__')
  end
end

# Guard on a sentinel that only this file defines (SimplyCouch::VERSION), not on
# the bare SimplyCouch constant. A plugin gem (e.g. simply_couch-couchbase) may
# open `module SimplyCouch` for its own version/namespace before this file loads;
# guarding on the bare module would then skip the library's whole initialization.
unless defined?(SimplyCouch::VERSION)
  $:<<(File.expand_path(File.dirname(__FILE__) + "/lib"))
  require 'simply_couch/instance_methods'
  require 'simply_couch/class_methods_base'

  module SimplyCouch
    VERSION = '1.0.0'
    class Error < RuntimeError; end
    class RecordNotFound < RuntimeError; end
    class NotImplementedError < RuntimeError; end
    class ModelNotInstantiatedError < RuntimeError; end
    # Backend-neutral storage errors. Adapters translate driver-specific
    # exceptions (CouchRest::NotFound, Couchbase::Error::*, …) into these so the
    # model layer never rescues a driver class. See SimplyCouch::Adapter.
    class NotFound < RuntimeError; end
    # Raised by an adapter when a view spec cannot be expressed on that backend
    # (e.g. a raw/custom JavaScript map/reduce view on Couchbase).
    class UnsupportedView < RuntimeError; end

    # CouchDB map/reduce functions are generated by interpolating class names,
    # association names and foreign keys into JavaScript source. Those tokens
    # must not contain characters that could terminate a JS string literal or
    # statement and inject arbitrary view code. For every valid Ruby class name
    # / property name this check is a no-op (the generated JS is byte-identical);
    # it only raises when a name contains a JS-breakout character.
    JS_VIEW_TOKEN_BREAKOUT = /['"\\;\n\r\t(){}]/.freeze

    # Validate one or more tokens before they are interpolated into a view
    # function. Accepts strings/symbols/nested arrays; nil entries are ignored.
    # Returns the tokens so it can be used inline.
    def self.assert_safe_view_token!(*tokens)
      tokens.flatten.compact.each do |token|
        string = token.to_s
        next if string.empty?
        if string =~ JS_VIEW_TOKEN_BREAKOUT
          raise SimplyCouch::Error,
            "unsafe value for CouchDB view generation: #{string.inspect}"
        end
      end
      tokens
    end
  end

  require 'simply_couch/adapter'
  require 'simply_couch/document_codec'
  require 'simply_couch/database_config'
  require 'simply_couch/model'
  require 'core_ext/time'
  require 'core_ext/date'
end
class SimplyCouch::Conflict < StandardError; end
